# GENERATED by tools/sdk-codegen - DO NOT EDIT.
"""Per-pack KiteFrost SDK for game-narrative (PPI-3)."""

from __future__ import annotations

from .client import GameNarrativeClient
from .version import PACK_SLUG, SDK_VERSION

__all__ = ["GameNarrativeClient", "PACK_SLUG", "SDK_VERSION"]
__version__ = SDK_VERSION
