# GENERATED by tools/sdk-codegen - DO NOT EDIT.
"""Per-pack client for game-narrative on top of kitefrost_core (PPI-3)."""

from __future__ import annotations

from kitefrost_core import KiteFrostCore

from .resources import CharactersResource, ContinuityResource, DialogueResource, FactionsResource, FeedbackResource, ItemsResource, LocationsResource, LoreBibleResource, ScenesResource, SeedsResource, SessionsResource, StoryArcsResource
from .version import PACK_SLUG, SDK_VERSION


class GameNarrativeClient:
    """Game Narrative pack client.

    Wraps a single shared ``KiteFrostCore`` so multiple per-pack clients
    can share one auth provider / connection pool (D-PPI-SDK-BUNDLING).
    """

    def __init__(self, core: KiteFrostCore) -> None:
        self.core = core
        self.characters = CharactersResource(core.transport)
        self.continuity = ContinuityResource(core.transport)
        self.dialogue = DialogueResource(core.transport)
        self.factions = FactionsResource(core.transport)
        self.feedback = FeedbackResource(core.transport)
        self.items = ItemsResource(core.transport)
        self.locations = LocationsResource(core.transport)
        self.lore_bible = LoreBibleResource(core.transport)
        self.scenes = ScenesResource(core.transport)
        self.seeds = SeedsResource(core.transport)
        self.sessions = SessionsResource(core.transport)
        self.story_arcs = StoryArcsResource(core.transport)

    @classmethod
    def from_api_key(cls, api_key: str, **kwargs: object) -> "GameNarrativeClient":
        """Build a client with its own shared core from an API key."""
        kwargs.setdefault("user_agent", f"kitefrost-{PACK_SLUG}/{SDK_VERSION}")
        return cls(KiteFrostCore(api_key=api_key, **kwargs))  # type: ignore[arg-type]
