# GENERATED by tools/sdk-codegen - DO NOT EDIT.
# Pack-specific resource layer on top of kitefrost_core (PPI-3).
# Regenerate deterministically from the stripped per-pack OpenAPI spec.

from __future__ import annotations

from typing import Any
from urllib.parse import quote

from kitefrost_core import Transport


class _BaseResource:
    def __init__(self, transport: Transport) -> None:
        self._t = transport


class CharactersResource(_BaseResource):
    """characters - pack-specific resource."""

    def audit_cast(self, project_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/characters/audit")

    def batch_create_characters(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/characters/batch", json=body)

    def batch_generate(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/characters/batch/generate", json=body)

    def create_characters(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/characters", json=body)

    def delete_characters(self, project_id: str, entity_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/game-narrative/characters/{quote(entity_id)}")

    def export_character(self, project_id: str, character_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/characters/{quote(character_id)}/export", json=body)

    def generate_dialogue(self, project_id: str, character_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/characters/{quote(character_id)}/generate", json=body)

    def get_characters(self, project_id: str, entity_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/characters/{quote(entity_id)}")

    def list_characters(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/characters", params=params)

    def refine_character(self, project_id: str, character_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/characters/{quote(character_id)}/refine", json=body)

    def synthesize_character_voice(self, project_id: str, character_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/characters/{quote(character_id)}/voice", json=body)

    def update_characters(self, project_id: str, entity_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/game-narrative/characters/{quote(entity_id)}", json=body)

class ContinuityResource(_BaseResource):
    """continuity - pack-specific resource."""

    def audit_files(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/continuity/audit-files", json=body)

    def check_continuity(self, project_id: str) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/continuity/check")

class DialogueResource(_BaseResource):
    """dialogue - pack-specific resource."""

    def create_graph(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues", json=body)

    def create_node(self, project_id: str, graph_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}/nodes", json=body)

    def create_variable(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/narrative-variables", json=body)

    def delete_graph(self, project_id: str, graph_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}")

    def delete_node(self, project_id: str, node_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/game-narrative/dialogue-nodes/{quote(node_id)}")

    def delete_variable(self, project_id: str, variable_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/game-narrative/narrative-variables/{quote(variable_id)}")

    def export_dialogue_graph(self, project_id: str, graph_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}/export", json=body)

    def generate_dialogue_graph(self, project_id: str, graph_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}/generate", json=body)

    def get_graph(self, project_id: str, graph_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}")

    def get_node(self, project_id: str, node_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/dialogue-nodes/{quote(node_id)}")

    def get_variable(self, project_id: str, variable_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/narrative-variables/{quote(variable_id)}")

    def import_dialogue_graph(self, project_id: str, graph_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}/import", json=body)

    def list_graphs(self, project_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues")

    def list_nodes(self, project_id: str, graph_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}/nodes")

    def list_variables(self, project_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/narrative-variables")

    def patch_graph(self, project_id: str, graph_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}", json=body)

    def patch_node(self, project_id: str, node_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/game-narrative/dialogue-nodes/{quote(node_id)}", json=body)

    def patch_variable(self, project_id: str, variable_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/game-narrative/narrative-variables/{quote(variable_id)}", json=body)

    def refine_dialogue_graph(self, project_id: str, graph_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}/refine", json=body)

    def simulate_dialogue_graph(self, project_id: str, graph_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}/simulate", json=body)

    def validate_dialogue_graph(self, project_id: str, graph_id: str) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/dialogues/{quote(graph_id)}/validate")

class FactionsResource(_BaseResource):
    """factions - pack-specific resource."""

    def create_factions(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/factions", json=body)

    def delete_factions(self, project_id: str, entity_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/game-narrative/factions/{quote(entity_id)}")

    def export_faction(self, project_id: str, faction_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/factions/{quote(faction_id)}/export", json=body)

    def generate_faction(self, project_id: str, faction_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/factions/{quote(faction_id)}/generate", json=body)

    def get_factions(self, project_id: str, entity_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/factions/{quote(entity_id)}")

    def list_factions(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/factions", params=params)

    def refine_faction(self, project_id: str, faction_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/factions/{quote(faction_id)}/refine", json=body)

    def update_factions(self, project_id: str, entity_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/game-narrative/factions/{quote(entity_id)}", json=body)

class FeedbackResource(_BaseResource):
    """feedback - pack-specific resource."""

    def admin_list_feedback_attachments(self, feedback_id: str) -> Any:
        return self._t.get(f"/v1/feedback/{quote(feedback_id)}/attachments")

    def feedback_envelope_schema(self) -> Any:
        return self._t.get("/v1/feedback/schema.json")

    def lookup_feedback(self, feedback_id: str) -> Any:
        return self._t.get(f"/v1/feedback/{quote(feedback_id)}")

    def request_attachment_upload_url(self, body: dict[str, Any]) -> Any:
        return self._t.post("/v1/feedback/attachments/upload-url", json=body)

    def submit_feedback_envelope(self) -> Any:
        return self._t.post("/v1/feedback")

class ItemsResource(_BaseResource):
    """items - pack-specific resource."""

    def create_items(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/items", json=body)

    def delete_items(self, project_id: str, entity_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/game-narrative/items/{quote(entity_id)}")

    def export_item(self, project_id: str, item_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/items/{quote(item_id)}/export", json=body)

    def generate_item(self, project_id: str, item_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/items/{quote(item_id)}/generate", json=body)

    def get_items(self, project_id: str, entity_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/items/{quote(entity_id)}")

    def list_items(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/items", params=params)

    def refine_item(self, project_id: str, item_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/items/{quote(item_id)}/refine", json=body)

    def update_items(self, project_id: str, entity_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/game-narrative/items/{quote(entity_id)}", json=body)

class LocationsResource(_BaseResource):
    """locations - pack-specific resource."""

    def create_locations(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/locations", json=body)

    def delete_locations(self, project_id: str, entity_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/game-narrative/locations/{quote(entity_id)}")

    def export_location(self, project_id: str, location_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/locations/{quote(location_id)}/export", json=body)

    def generate_location(self, project_id: str, location_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/locations/{quote(location_id)}/generate", json=body)

    def get_locations(self, project_id: str, entity_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/locations/{quote(entity_id)}")

    def list_locations(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/locations", params=params)

    def refine_location(self, project_id: str, location_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/locations/{quote(location_id)}/refine", json=body)

    def update_locations(self, project_id: str, entity_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/game-narrative/locations/{quote(entity_id)}", json=body)

class LoreBibleResource(_BaseResource):
    """lore-bible - pack-specific resource."""

    def generate_lore_bible(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/lore-bible/generate")

class ScenesResource(_BaseResource):
    """scenes - pack-specific resource."""

    def create_scene(self, project_id: str) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/scenes")

    def delete_scene(self, project_id: str, session_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/game-narrative/scenes/{quote(session_id)}")

    def export_scene(self, project_id: str, session_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/scenes/{quote(session_id)}/export", json=body)

    def generate_scene(self, project_id: str, session_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/scenes/{quote(session_id)}/generate", json=body)

    def get_scene(self, project_id: str, session_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/scenes/{quote(session_id)}")

    def patch_scene(self, project_id: str, session_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/game-narrative/scenes/{quote(session_id)}", json=body)

    def refine_scene(self, project_id: str, session_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/scenes/{quote(session_id)}/refine", json=body)

class SeedsResource(_BaseResource):
    """seeds - pack-specific resource."""

    def batch_reject_seeds(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/seeds/batch/reject", json=body)

    def batch_validate_seeds(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/seeds/batch/validate", json=body)

    def delete_seed(self, project_id: str, seed_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/seeds/{quote(seed_id)}")

    def generate_seeds(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/seeds/generate", json=body)

    def get_seed(self, project_id: str, seed_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/seeds/{quote(seed_id)}")

    def list_seeds(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/seeds", params=params)

    def patch_seed(self, project_id: str, seed_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/seeds/{quote(seed_id)}", json=body)

    def promote_seed(self, project_id: str, seed_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/seeds/{quote(seed_id)}/promote", json=body)

class SessionsResource(_BaseResource):
    """sessions - pack-specific resource."""

    def create_snapshot(self, session_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/sessions/{quote(session_id)}/snapshot", json=body)

    def get_session_status(self, session_id: str) -> Any:
        return self._t.get(f"/v1/sessions/{quote(session_id)}/status")

    def hitl_respond(self, session_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/sessions/{quote(session_id)}/respond", json=body)

    def stream_session_events(self, session_id: str) -> Any:
        return self._t.get(f"/v1/sessions/{quote(session_id)}/stream")

class StoryArcsResource(_BaseResource):
    """story-arcs - pack-specific resource."""

    def create_story_arc(self, project_id: str) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/story-arcs")

    def delete_story_arc(self, project_id: str, quest_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/game-narrative/story-arcs/{quote(quest_id)}")

    def export_quest(self, project_id: str, quest_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/story-arcs/{quote(quest_id)}/export", json=body)

    def generate_quest(self, project_id: str, quest_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/story-arcs/{quote(quest_id)}/generate", json=body)

    def get_quest(self, project_id: str, quest_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/game-narrative/story-arcs/{quote(quest_id)}")

    def patch_quest(self, project_id: str, quest_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/game-narrative/story-arcs/{quote(quest_id)}", json=body)

    def refine_quest(self, project_id: str, quest_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/game-narrative/story-arcs/{quote(quest_id)}/refine", json=body)
