# GENERATED by tools/sdk-codegen - DO NOT EDIT.
"""Per-pack KiteFrost SDK for ttrpg-gm (PPI-3)."""

from __future__ import annotations

from .client import TtrpgGmClient
from .version import PACK_SLUG, SDK_VERSION

__all__ = ["TtrpgGmClient", "PACK_SLUG", "SDK_VERSION"]
__version__ = SDK_VERSION
