# GENERATED by tools/sdk-codegen - DO NOT EDIT.
"""Per-pack client for ttrpg-gm on top of kitefrost_core (PPI-3)."""

from __future__ import annotations

from kitefrost_core import KiteFrostCore

from .resources import FactionsResource, FeedbackResource, ItemsResource, LocationsResource, NpcsResource, PlacesResource, PlayersResource, SeedsResource, SessionsResource, TtrpgResource
from .version import PACK_SLUG, SDK_VERSION


class TtrpgGmClient:
    """Ttrpg Gm pack client.

    Wraps a single shared ``KiteFrostCore`` so multiple per-pack clients
    can share one auth provider / connection pool (D-PPI-SDK-BUNDLING).
    """

    def __init__(self, core: KiteFrostCore) -> None:
        self.core = core
        self.factions = FactionsResource(core.transport)
        self.feedback = FeedbackResource(core.transport)
        self.items = ItemsResource(core.transport)
        self.locations = LocationsResource(core.transport)
        self.npcs = NpcsResource(core.transport)
        self.places = PlacesResource(core.transport)
        self.players = PlayersResource(core.transport)
        self.seeds = SeedsResource(core.transport)
        self.sessions = SessionsResource(core.transport)
        self.ttrpg = TtrpgResource(core.transport)

    @classmethod
    def from_api_key(cls, api_key: str, **kwargs: object) -> "TtrpgGmClient":
        """Build a client with its own shared core from an API key."""
        kwargs.setdefault("user_agent", f"kitefrost-{PACK_SLUG}/{SDK_VERSION}")
        return cls(KiteFrostCore(api_key=api_key, **kwargs))  # type: ignore[arg-type]
