# GENERATED by tools/sdk-codegen - DO NOT EDIT.
# Pack-specific resource layer on top of kitefrost_core (PPI-3).
# Regenerate deterministically from the stripped per-pack OpenAPI spec.

from __future__ import annotations

from typing import Any
from urllib.parse import quote

from kitefrost_core import Transport


class _BaseResource:
    def __init__(self, transport: Transport) -> None:
        self._t = transport


class FactionsResource(_BaseResource):
    """factions - pack-specific resource."""

    def create_factions(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/factions", json=body)

    def delete_factions(self, project_id: str, entity_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/ttrpg-gm/factions/{quote(entity_id)}")

    def get_factions(self, project_id: str, entity_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/factions/{quote(entity_id)}")

    def list_factions(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/factions", params=params)

    def update_factions(self, project_id: str, entity_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/ttrpg-gm/factions/{quote(entity_id)}", json=body)

class FeedbackResource(_BaseResource):
    """feedback - pack-specific resource."""

    def admin_list_feedback_attachments(self, feedback_id: str) -> Any:
        return self._t.get(f"/v1/feedback/{quote(feedback_id)}/attachments")

    def feedback_envelope_schema(self) -> Any:
        return self._t.get("/v1/feedback/schema.json")

    def lookup_feedback(self, feedback_id: str) -> Any:
        return self._t.get(f"/v1/feedback/{quote(feedback_id)}")

    def request_attachment_upload_url(self, body: dict[str, Any]) -> Any:
        return self._t.post("/v1/feedback/attachments/upload-url", json=body)

    def submit_feedback_envelope(self) -> Any:
        return self._t.post("/v1/feedback")

class ItemsResource(_BaseResource):
    """items - pack-specific resource."""

    def create_items(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/items", json=body)

    def delete_items(self, project_id: str, entity_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/ttrpg-gm/items/{quote(entity_id)}")

    def get_items(self, project_id: str, entity_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/items/{quote(entity_id)}")

    def list_items(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/items", params=params)

    def update_items(self, project_id: str, entity_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/ttrpg-gm/items/{quote(entity_id)}", json=body)

class LocationsResource(_BaseResource):
    """locations - pack-specific resource."""

    def create_locations(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/locations", json=body)

    def delete_locations(self, project_id: str, entity_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/ttrpg-gm/locations/{quote(entity_id)}")

    def get_locations(self, project_id: str, entity_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/locations/{quote(entity_id)}")

    def list_locations(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/locations", params=params)

    def update_locations(self, project_id: str, entity_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/ttrpg-gm/locations/{quote(entity_id)}", json=body)

class NpcsResource(_BaseResource):
    """npcs - pack-specific resource."""

    def create_npcs(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/npcs", json=body)

    def delete_npcs(self, project_id: str, entity_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/ttrpg-gm/npcs/{quote(entity_id)}")

    def get_npcs(self, project_id: str, entity_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/npcs/{quote(entity_id)}")

    def list_npcs(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/npcs", params=params)

    def update_npcs(self, project_id: str, entity_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/ttrpg-gm/npcs/{quote(entity_id)}", json=body)

class PlacesResource(_BaseResource):
    """places - pack-specific resource."""

    def create_places(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/places", json=body)

    def delete_places(self, project_id: str, entity_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/ttrpg-gm/places/{quote(entity_id)}")

    def get_places(self, project_id: str, entity_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/places/{quote(entity_id)}")

    def list_places(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/places", params=params)

    def update_places(self, project_id: str, entity_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/ttrpg-gm/places/{quote(entity_id)}", json=body)

class PlayersResource(_BaseResource):
    """players - pack-specific resource."""

    def create_players(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/players", json=body)

    def delete_players(self, project_id: str, entity_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/ttrpg-gm/players/{quote(entity_id)}")

    def get_players(self, project_id: str, entity_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/players/{quote(entity_id)}")

    def list_players(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/players", params=params)

    def update_players(self, project_id: str, entity_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/ttrpg-gm/players/{quote(entity_id)}", json=body)

class SeedsResource(_BaseResource):
    """seeds - pack-specific resource."""

    def batch_reject_seeds(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/seeds/batch/reject", json=body)

    def batch_validate_seeds(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/seeds/batch/validate", json=body)

    def delete_seed(self, project_id: str, seed_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/seeds/{quote(seed_id)}")

    def generate_seeds(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/seeds/generate", json=body)

    def get_seed(self, project_id: str, seed_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/seeds/{quote(seed_id)}")

    def list_seeds(self, project_id: str, params: dict[str, Any] | None = None) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/seeds", params=params)

    def patch_seed(self, project_id: str, seed_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/seeds/{quote(seed_id)}", json=body)

    def promote_seed(self, project_id: str, seed_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/seeds/{quote(seed_id)}/promote", json=body)

class SessionsResource(_BaseResource):
    """sessions - pack-specific resource."""

    def create_snapshot(self, session_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/sessions/{quote(session_id)}/snapshot", json=body)

    def get_session_status(self, session_id: str) -> Any:
        return self._t.get(f"/v1/sessions/{quote(session_id)}/status")

    def hitl_respond(self, session_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/sessions/{quote(session_id)}/respond", json=body)

    def stream_session_events(self, session_id: str) -> Any:
        return self._t.get(f"/v1/sessions/{quote(session_id)}/stream")

class TtrpgResource(_BaseResource):
    """ttrpg - pack-specific resource."""

    def check_journal_continuity(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/continuity/check", json=body)

    def check_markdown_notes(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/continuity/check-notes", json=body)

    def create_encounter(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/encounters", json=body)

    def create_note(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/notes", json=body)

    def create_quest(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/quests", json=body)

    def create_session(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/sessions", json=body)

    def delete_encounter(self, project_id: str, encounter_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/ttrpg-gm/encounters/{quote(encounter_id)}")

    def delete_note(self, project_id: str, note_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/ttrpg-gm/notes/{quote(note_id)}")

    def delete_quest(self, project_id: str, quest_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/ttrpg-gm/quests/{quote(quest_id)}")

    def delete_session(self, project_id: str, session_id: str) -> Any:
        return self._t.delete(f"/v1/projects/{quote(project_id)}/ttrpg-gm/sessions/{quote(session_id)}")

    def generate_encounter(self, project_id: str, encounter_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/encounters/{quote(encounter_id)}/generate", json=body)

    def generate_quest(self, project_id: str, quest_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/quests/{quote(quest_id)}/generate", json=body)

    def generate_session(self, project_id: str, session_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/sessions/{quote(session_id)}/generate", json=body)

    def get_encounter(self, project_id: str, encounter_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/encounters/{quote(encounter_id)}")

    def get_note(self, project_id: str, note_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/notes/{quote(note_id)}")

    def get_quest(self, project_id: str, quest_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/quests/{quote(quest_id)}")

    def get_session(self, project_id: str, session_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/sessions/{quote(session_id)}")

    def import_vtt_commit(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/import/vtt/commit", json=body)

    def import_vtt_route(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/import/vtt", json=body)

    def list_encounters(self, project_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/encounters")

    def list_notes(self, project_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/notes")

    def list_quests(self, project_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/quests")

    def list_sessions(self, project_id: str) -> Any:
        return self._t.get(f"/v1/projects/{quote(project_id)}/ttrpg-gm/sessions")

    def quick_dialogue(self, project_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/quick-dialogue", json=body)

    def refine_quest(self, project_id: str, quest_id: str, body: dict[str, Any]) -> Any:
        return self._t.post(f"/v1/projects/{quote(project_id)}/ttrpg-gm/quests/{quote(quest_id)}/refine", json=body)

    def update_encounter(self, project_id: str, encounter_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/ttrpg-gm/encounters/{quote(encounter_id)}", json=body)

    def update_note(self, project_id: str, note_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/ttrpg-gm/notes/{quote(note_id)}", json=body)

    def update_quest(self, project_id: str, quest_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/ttrpg-gm/quests/{quote(quest_id)}", json=body)

    def update_session(self, project_id: str, session_id: str, body: dict[str, Any]) -> Any:
        return self._t.patch(f"/v1/projects/{quote(project_id)}/ttrpg-gm/sessions/{quote(session_id)}", json=body)
